name: Commit Analysis

on:
  pull_request:
    # types: [closed]
    types: [opened, synchronize]
    branches:
      - main  # or master, depending on your default branch name
      - master
      - feat/qwerty

jobs:
  commit-analysis:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history for git blame to work correctly
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          pip install GitPython requests
      - name: Make commit analysis script executable
        run: chmod +x .github/scripts/commit_analysis_modified.py
      - name: Run commit analysis script
        env:
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_REPOSITORY_ID: ${{ github.event.repository.id }}
          GITHUB_ORGANIZATION_ID: ${{ github.event.repository.owner.id }}
          API_URL: https://smee.io/WM3TsYqgTQryj0Vu
        run: python .github/scripts/commit_analysis_modified.py
