name: PR Commit Analysis

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  analyze-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Get list of commits in PR
        id: get_commits
        run: |
          PR_COMMITS=$(git log --pretty=format:"%H" origin/${{ github.base_ref }}..HEAD | tail -n +2 | tr '\n' ' ')
          echo "PR_COMMITS=$PR_COMMITS"
          echo "PR_COMMITS=$PR_COMMITS" >> $GITHUB_ENV

      - name: Analyze modified lines in each commit
        run: |
          for commit in $PR_COMMITS; do
            echo "Analyzing commit: $commit"

            # Get changed files (filtering out metadata and ensuring file exists)
            git show --pretty="" --name-status $commit | while read status file; do
              # Ensure file is not empty and exists in the repo
              if [[ -z "$file" || ! -f "$file" ]]; then
                echo "Skipping missing file: $file"
                continue
              fi

              echo "Processing file: $file with status: $status"

              # Extract modified line numbers
              git diff --unified=0 $commit^ $commit -- $file | grep -E "^@@" | \
                awk -F' ' '{print $2}' | sed 's/[^0-9,]//g' | while read line_range; do
                  start_line=$(echo $line_range | cut -d, -f1)
                  end_line=$((start_line + $(echo $line_range | cut -d, -f2) - 1))

                  echo "Modified lines: $start_line-$end_line in $file"

                  # Ensure valid line range before running git log -L
                  if [[ -n "$start_line" && -n "$end_line" && "$start_line" -le "$end_line" ]]; then
                    commit_history=$(git log -p -L $start_line,$end_line:$file 2>/dev/null | grep "commit " | awk '{print $2}')
                  else
                    echo "Invalid line range: $start_line-$end_line in $file"
                    continue
                  fi

                  # Extract last two commits and compute time difference
                  last_two_commits=($(echo "$commit_history" | head -n 2))
                  if [[ ${#last_two_commits[@]} -eq 2 ]]; then
                    date1=$(git show -s --format=%ct ${last_two_commits[0]})
                    date2=$(git show -s --format=%ct ${last_two_commits[1]})
                    duration=$((date1 - date2))
                    echo "Duration between last two commits: $duration seconds"
                  else
                    echo "Not enough commit history for duration calculation"
                  fi
                done
            done
          done
